### PR TITLE
Restricting posts access

### PR DESCRIPTION
**Pull request by TimRobinson1**
The ```resources :posts``` was duplicated and was placed outside of the Clearance SignedIn Constraint, giving access to the newsfeed for users who weren't logged in.  Just removed the extra posts resources and adjusted a test that relied on visiting the posts page when signed out.

I'm not sure about the test and whether or not it was adjusted appropriately, please let me know what you think/suggest something you think might work better.

### CODE REVIEW

**Review by ns-winter — APPROVED** [review]
Does what it says on the tin.  Looks good to Bertie & I!

**Review by neoeno — APPROVED** [review]
Looks good. I reckon everyone trying to resolve merge conflicts at once means sometimes stuff sneaks back in. Maybe something worth mulling over.

**Comment by TimRobinson1** [comment]
I'm trying to follow the provided git steps to merge (due to the conflicting test file, I can't auto-merge) and I've come against ```master (protected branch hook declined)```.

**Comment by neoeno** [comment]
Come over tomorrow and we'll sort it!

**Comment by TimRobinson1** [comment]
Any ideas as to what that strange Integer/Proc error is referring to, @neoeno ?  I'm doing my best to google the issue (and the test is passing locally), but not on Travis there.  Nevermind!  Ran Travis again and it.. worked?  So, not sure what happened there.

**Comment by neoeno** [comment]
@TimRobinson1 Oh, I missed this and I also didn't see the build! Still — seems like it worked out okay.

**Pull request merged**
