### PR TITLE
add migration file to iterate through invalid comments and assign the…

### PR DESCRIPTION
**Pull request by JayWebDevCom**
This PR should add a migration file to iterate through invalid comments and assign them the user_id of the Anonymous User where necessary.

### CODE REVIEW

**Review by adamjohnsnow — APPROVED** [review]
Good work dude. @neoeno happy?

**Comment by BertZZ** [comment]
@JayWebDevCom Will this one fix Heroku??

**Comment by JayWebDevCom** [comment]
@BertZZ  If the problem is as I suspect that comments may have been made by users not logged in i.e. having no user_id value to be assigned to their associated comment, the yes it should :)

**Review by neoeno — APPROVED** [review]
I'm convinced!

**Comment by BertZZ** [comment]
DO IT

**Pull request merged**
