### PR TITLE
fixes old posts without userIds

### PR DESCRIPTION
**Pull request by adamjohnsnow**

### CODE REVIEW

**Review by JayWebDevCom — APPROVED** [review]
Short. Sharp. Sweet.

**Review by neoeno — CHANGES_REQUESTED** [review]
As discussed, it still errors!

**Comment by adamjohnsnow** [comment]
Have I fixed it??

**Review by neoeno — APPROVED** [review]
Like I said — make sure you take the opportunity to refactor if this conditional starts multiplying.

**Pull request merged**
