### PR TITLE
Added comment model to the DB

### PR DESCRIPTION
**Pull request by BertZZ**

### CODE REVIEW

**Comment by henryhobhouse** [comment]
Hey @BertZZ 

Thoughts 

1. could make comments body null : false (can't be empty)
2. could make comments body to have max length 

The rest of the code looks good! Nice job 👍

**Comment by BertZZ** [comment]
Ill look Into this now

**Comment by neoeno** [comment]
Let me know when it's updated!

**Comment by henryhobhouse** [comment]
@BertZZ you will need to add a .travis.yml file to pass travis now. You should simply be able to copy the one from master. 

I would also suggest adding a way to prevent a null value, and limit length, in the comments body at the database level in addition to client(ish)/model. Compare the db schema for posts and your comments and adjust your migration file accordingly.

**Comment by BertZZ** [comment]
Ok, I might have a look at this tonight or tomorrow morning. I pulled the .travis.yml file from the master but I think I may need a new pull request for it to see that I have it now as I can't commit any new changes as it says my branch is up to date

**Pull request closed without merging**
