### PR TITLE
short term fix for comments without usernames

### PR DESCRIPTION
**Pull request by adamjohnsnow**

### CODE REVIEW

**Review by BertZZ — APPROVED** [review]
Looks good. Get this merged

**Review by neoeno — CHANGES_REQUESTED** [review]
I think these 'quick fixes' are actually costing us quite a lot of time!

Look at #37 — it won't take long to implement that for comments. It's also a more robust solution that will save us from all of these sorts of errors across everyone in the team.

**Comment by BertZZ** [comment]
If we are not merging this can we delete it?

**Comment by adamjohnsnow** [comment]
Not needed

**Pull request closed without merging**
